x-default-env: &default-env
  WS_APIKEY: # https://steamcommunity.com/dev/apikey
  FASTDL_URL: https://fastdl.somedomain.com/ # fastdl base url
  STEAMGROUP: 0
  CONTACT: admin@somedomain.com

services:
  tf2watchdog:
    image: tf2watchdog
    container_name: tf2watchdog
    restart: unless-stopped
    user: 1000:1000
    tty: true
    stdin_open: true
    volumes:
      - ./watchdog:/watchdog
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    network_mode: bridge
  tf2-server-1:
    image: tf2server
    container_name: tf2-server-1
    restart: unless-stopped
    user: 1000:1000
    tty: true
    stdin_open: true
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    network_mode: host
    environment:
      <<: *default-env
      ID: 1 # unique ID for this server, used for mount folders
      HOSTNAME: Kreedz | EU | Public | 128t VNL Global
      GSLT: "" # https://steamcommunity.com/dev/managegameservers
      IP: 0.0.0.0
      IP_DOMAIN: somedomain.com
      PORT: 27015
      RCON_PASSWORD: changeme
      PASSWORD: ""
      TICKRATE: 128
      EXTRA_LAUNCH_OPTS: "" # extra launch options
      MAP: ctf_2fort
      REGION: EU # server region code (EU, NA)
      TAGS: eu,public,tf2 # comma separated list of tags
      # Database settings
      DB_PORT: 3306
      DB_HOST: localhost
      DB_DRIVER: sqlite
      DB_USER: root
      DB_PASS: ""
      DB_TICKRATE_NAME: sourcemod_128 # tickrate specific db name, e.g for gokz
      DB_SHARED_NAME: sourcemod # shared/global db name, e.g for clientprefs
      SBPP_SERVERID: -1 # sourcebans++ server ID, -1 to disable
      WHITELIST: false  # enable whitelist-only mode (true/false)
      AC: true # enable CowAC & AntiDLL (true/false)
      ABH: false # enable ABH (true/false)
      MODE: "" # server mode (server specific configs)
    volumes:
      - ./watchdog:/watchdog
      - ./layers:/layers:ro
      - ./mounts:/mounts
      - ./user:/user:ro
