FROM registry.gitlab.steamos.cloud/steamrt/sniper/sdk

RUN apt-get update \
    && apt-get install -y --no-install-recommends --no-install-suggests \
        jq python3 python3-pip python3-requests python3-xmltodict libssl-dev:i386 \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY tf2server.sh /app/tf2server.sh
COPY run.sh /user/run.sh
RUN chmod 555 /app/tf2server.sh /user/run.sh

WORKDIR /
ENTRYPOINT ["/app/tf2server.sh"]
